version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: laliga
    volumes:
      - ./postgres/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  etl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etl_container
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: laliga
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - .:/app
    command: >
      sh -c "until pg_isready -h postgres -p 5432; do echo 'Waiting for PostgreSQL...'; sleep 2; done &&
      python etl/main.py"