version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: laliga_user
      POSTGRES_PASSWORD: laliga_pass
      POSTGRES_DB: laliga
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  etl:
    build:
      context: .
      dockerfile: Dockerfile.etl
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: laliga
      DB_USER: laliga_user
      DB_PASSWORD: laliga_pass